import '@styles/scss/globals.scss';
import '@utils/i18n';
import 'reflect-metadata';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { Bounce, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { PersistGate } from 'redux-persist/integration/react';
import { Container } from '@mui/material';
import { ThemeProvider, useTheme } from '@mui/material/styles';
import { AppStore, persistor } from '@store/store';
import customTheme from '@styles/theme';
import { throwErrorIfEnvVarsNotFound } from '@utils/ConfigUtils';

const App = (props: any) => {
  throwErrorIfEnvVarsNotFound();

  const { Component, pageProps } = props;
  const outerTheme: any = useTheme();
  const Header = dynamic(() => import('@components/layouts/Header'), { ssr: false });
  const Footer = dynamic(() => import('@components/layouts/Footer'), { ssr: false });

  return (
    <Provider store={AppStore}>
      <PersistGate persistor={persistor}>
        <Head>
          <title>Fpool</title>
          <meta name="description" content="Generated by create-wc-dapp" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" type="image/png" href="/assets/favicon-96x96.png" sizes="96x96"></link>
          <link rel="icon" href="/assets/favicon.ico" type="image/x-icon" />
          <link rel="shortcut icon" href="/assets/favicon.ico"></link>
          <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"></link>
          <meta name="apple-mobile-web-app-title" content="Fpool"></meta>
          <link rel="manifest" href="/assets/site.webmanifest"></link>
        </Head>
        <ThemeProvider theme={customTheme(outerTheme)}>
          <Header />
          <Container
            sx={{
              marginTop: '69px',
              px: { xs: 1, md: 5 },
              py: { xs: 1, md: 1 },
              display: 'flex',
              flexDirection: 'column'
            }}>
            <Component {...pageProps} />
          </Container>

          <Footer />
          <ToastContainer
            className="custom-toast-container"
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
        </ThemeProvider>
      </PersistGate>
    </Provider>
  );
};

export default App;
